site_name: HPE Storage Array Exporter for Prometheus
site_description: Reference documentation for the HPE Storage Array Exporter for Prometheus
site_url: https://hpe-storage.github.io/array-exporter
site_author: Hewlett Packard Enterprise
theme:
  name: readthedocs
  custom_dir: hpe_theme/
repo_name: 'hpe-storage/array-exporter'
repo_url: 'https://github.com/hpe-storage/array-exporter'
copyright: "Copyright 2021 Hewlett Packard Enterprise Development LP"
extra_css:
  - css/hpedev.css
use_directory_urls: false
markdown_extensions:
  - admonition:
  - toc:
      permalink: True
      separator: "_"
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'
plugins:
  - search:
  - macros:
      include_dir: '.'
nav:
  - GET STARTED:
    - 'Releases': releases/index.md
    - 'Deployment': deployment/index.md
    - 'Metrics': metrics/index.md
    - 'Prometheus Integration': integration/index.md
    - 'Grafana Dashboards': grafana/index.md
  - COMMUNITY:
    - 'HPE Developer Community': 'https://developer.hpe.com'
    - 'Sign up to HPE DEV on Slack': 'https://slack.hpedev.io'
    - 'Got feedback?': 'https://github.com/hpe-storage/array-exporter/issues/new?title=I have some feedback on the Array Exporter'
  - LEGAL:
    - 'End User License Agreement': 'legal/eula/index.md'
    - 'Notices': 'legal/notices/index.md'
    - 'Support': 'legal/support/index.md'
